.TH CRC-CLI "1" "June 2016" "crowdclassic-cli 0.12"
.SH NAME
crowdclassic-cli \- a remote procedure call client for CRowdCLassic Core.
.SH SYNOPSIS
crowdclassic-cli [options] <command> [params] \- Send command to CRowdCLassic Core.
.TP
crowdclassic-cli [options] help \- Asks CRowdCLassic Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the crowdclassic-cli program. crowdclassic-cli is an RPC client used to send commands to CRowdCLassic Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBcrowdclassicd\fP, \fBcrowdclassic.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
